### ISSUE TITLE
[BUG] - Gap in integration weights uploaded to SHFQA

### ISSUE THREAD

**Issue by glkrylov** [zhinst/laboneq#1]
**Describe the bug**
Integration weights queried from the SHFQA have a gap where the integration weight is zero.
This gap is 48 samples in the middle of a 2 us acquisition, but can be much larger for other lengths of acquire signals (e.g. over 400 samples for 1.6 us). 
Waveforms in the compiled experiment do not have this gap.

**To Reproduce**
1. Perform any experiment using an acquire line on SHFQA
2. Use zhinst.ziPython.ziDAQServer to query device node /dev12***/qachannels/0/readout/integration/weights/0/wave 

**Expected behavior**
Integration weights corresponding to the waveforms in the compiled experiment.

**Code & Screenshots**
Attached are a zip file with experiment.json and setup.json and a screenshot of the observed gap

**Versions used:**
 - laboneq 1.0.2
 - zhinst-core 22.8.35048

[exp_setup.zip](https://github.com/zhinst/laboneq/files/9715529/exp_setup.zip)
![Screenshot from 2022-10-05 14-21-27](https://user-images.githubusercontent.com/175056/194059461-ec09020b-5daa-44eb-99bf-26a056be1229.png)

**Comment by QuantumClemens** [comment]
Hi Gleb,
thanks for reporting, we just confirmed that this is an issue in the current version of LabOne 22.8. and will be fixed in an upcoming patch release of the SHFQA firmware. Will let you know once that is released, but is planned soon.

**Comment by QuantumClemens** [comment]
This issue should be fixed with the new LabOne firmware, which LabOne Q will now depend on. When installing LabOne Q, make sure to also update the firmware on your instruments through the LabOne GUI. 
Closing this issue.
