### ISSUE TITLE
[Feature] Waveform replacement of rf pulses

### ISSUE THREAD

**Issue by GlaserN** [zhinst/laboneq#12]
**Is your feature request related to a problem?  Please describe.**
Enable waveform replacement in neartime loops on rf signal channels.

**Is your feature request related to new experiments? Please describe.**

**Describe the solution you'd like**

**Describe alternatives or workarounds you have considered**

**Context**

**Comment by Alectoid** [comment]
Hi @GlaserN , 

LabOne Q supports waveform exchanges during the near-time parts of the experiment:

You can replace a pulse in the current experiment using `Session.replace_pulse`; alternatively, you can replace a pulse in a compiled experiment, via `CompiledExperiment.replace_pulse`, see the API documentation https://docs.zhinst.com/labone_q_api/apidocs/laboneq.core.types.html#laboneq.core.types.compiled_experiment.CompiledExperiment.replace_pulse

A small example how to replace a pulse via a call-back function in the near-time part of an experiment is given here: https://github.com/zhinst/laboneq/blob/main/examples/user_functions.ipynb

Is this what you were looking for? Let us know if you have more questions.

**Comment by Alectoid** [comment]
Hi @GlaserN,
We have just verified on hardware that the feature works. Attached is a notebook (had to zip it because github would not allow me to upload as is) with a small example. Does this work for you?

[WaveformExchangeRfLines.zip](https://github.com/zhinst/laboneq/files/10023754/WaveformExchangeRfLines.zip)

**Comment by Alectoid** [comment]
Another update: In the specific use case where only one channel of an AWG core is active, waveform replacement indeed does not work. We will fix this soon. In a workaround, you could play zeros on the second AWG channel.

**Comment by Alectoid** [comment]
Hi @GlaserN , with the next release, the waveform exchange will be possible also on a single RF line on an HDAWG. I'll close this issue shortly after the relaese.

**Comment by Alectoid** [comment]
Resolved in 1.6, released yesterday. Will close this issue now.
