### ISSUE TITLE
[BUG] - Loops of repeated instructions not combined into seqc loops.

### ISSUE THREAD

**Issue by GlaserN** [zhinst/laboneq#13]
**Describe the bug**
Especially on the UHFQA with it's limited instruction memory we notice that repeating the same measurement in same intervals leads to N repetitions of the same instruction blocks. This leads to not being able to perform more than 50 measurements on the UHFQA, e.g., as for example in the following example.

**To Reproduce**
[experiment.zip](https://github.com/zhinst/laboneq/files/10177390/experiment.zip)
Compile the attached experiment and try to run it on a UHFQA device.

The UHFQA compiler will notice that too many instructions are used. Looking at the generated seqc code: i.e.:

[seq_UHFQA1_0.txt](https://github.com/zhinst/laboneq/files/10177429/seq_UHFQA1_0.txt)

shows that alot of repetions can be combined into a small loop. Performing this step will make the execution of a long experiment possible.

**Versions used:**
 - laboneq: 1.4
 - zhinst-core
 - others

**Context**
- [ ] Do you know a workaround for the issue? If yes, please provide a short description. 
  Manually postprocess seqc code (dangerous)
- [ ] Does the issue block your experiments?

**Comment by mforoozandeh** [comment]
Hi @GlaserN,

Thanks for reporting this. We will investigate and get back to you soon.

**Comment by QuantumClemens** [comment]
Hi @GlaserN ,
the code compression was significantly improved with release 2.4, I will close this ticket. Let us know if you find other issues.
