### ISSUE TITLE
[BUG] - Serializer problem for constant pulse

### ISSUE THREAD

**Issue by YuanG13** [zhinst/laboneq#15]
**Describe the bug**
If there is constant pulse in the experiment, serializer cannot deserialise the compiled experiment properly. It will return an error `__init__() missing 1 required positional argument: 'mixer_type'`

The error is expected to be the consequence of release 1.3, although we are testing in 1.4
**To Reproduce**
1. Define pulse sequence...
2. Execute on hardware / in emulation ...
3. Do additional steps...

run the following notebook in the laboneq example folder. it is modified from basic experiment
[serializer_error.zip](https://github.com/zhinst/laboneq/files/10187737/serializer_error.zip)

**Expected behavior**

**Code & Screenshots**
If possible, add example code or serialized LabOne Q data objects, like the Experiment and DeviceSetup, that allow us to reproduce the behavior. 

**Versions used:**
 - laboneq 1.4
 - zhinst-core 22.8
 - others

**Context**
- [ ] Do you know a workaround for the issue? If yes, please provide a short description. 
- [x] Does the issue block your experiments?

**Comment by YuanG13** [comment]
If the compiled experiment does not go through the serializer, there won't be an error

**Comment by polwel** [comment]
Hi Yuan, thanks for reporting, looking at fixing this ASAP.

**Comment by YuanG13** [comment]
does this mixer_type for pulse should be considered when we define the experiment, or this should be handled by laboneq? I did not see any instructions/examples for this.

**Comment by QuantumClemens** [comment]
fixed in 1.5, closing this issue
