### ISSUE TITLE
[BUG] - Serializer Problem for Oscillators in Calibration

### ISSUE THREAD

**Issue by YuanG13** [zhinst/laboneq#16]
**Describe the bug**

If there is a same oscillator (with identical uid) in both device setup calibration and experiment calibration, and the laboneq experiment has gone through the serializer, then the compiled experiment cannot be serialised anymore.

If the laboneq experiment does not go through the serializer, everything will be executed correctly.

The reason we were doing identical uid oscillator is because in previous version, laboneq requires that if several logical lines share one physical port, they need to either have only one calibration set with local oscillator or all of them use the identical oscillator with same uid(it is not possible that those oscillator share all other attributes but uid)

**To Reproduce**
1. Define pulse sequence...
2. Execute on hardware / in emulation ...
3. Do additional steps...

run the following notebook in example folder, this is modified from basic experiment

[calibration_error.zip](https://github.com/zhinst/laboneq/files/10189193/calibration_error.zip)

**Expected behavior**

**Code & Screenshots**
If possible, add example code or serialized LabOne Q data objects, like the Experiment and DeviceSetup, that allow us to reproduce the behavior. 

**Versions used:**
 - laboneq 1.4
 - zhinst-core 22.8
 - others

**Context**
- [ ] Do you know a workaround for the issue? If yes, please provide a short description. 
- [ ] Does the issue block your experiments?

**Comment by YuanG13** [comment]
This is actually not blocking our experiment, and it is not a serious issue. But this error should not happen in serializer at least.

**Comment by QuantumClemens** [comment]
Hi @YuanG13, thanks for reporting, to clarify, it was not clear to me from the description, are you assigning the same oscillator object to different lines or are these different oscillator objects but with the same uid?

**Comment by YuanG13** [comment]
same object to the same line, but one in devicesetup calibration (baseline calibration), one in experiment calibration.

**Comment by QuantumClemens** [comment]
Hi @YuanG13 ,
Looking at your experiment, what you are trying to do is assign the same oscillator object taken from the device setup calibration also to the experiment calibration - Definitely a bug that the serializer complains about duplicate uids here, this should be the same object internally. We are looking into it. 
In the meantime, there is a very simple workaround - do not define the local_oscillator in the experimental calibration. In this case, the baseline calibration property is used for the experiment, which is exactly what you want. Hope this helps, let me know if anything is unclear.

**Comment by polwel** [comment]
Hi Yuan,

Thanks for reporting.

The issue you're observing comes from the fact that you are sharing the same oscillator object between device setup and experiment. After a serialization round trip, experiment and setup are now decoupled. In particular the respective oscillators are now distinct objects (although with the same attributes, including UID). We disallow reusing UIDs, although in this case the compiler is not complaining, and does produce an (arguably invalid) `CompiledExperiment`. The serializer is not so lenient and objects.

The work around is simple: **Do not use the same UID (or even object) across device setup and experiment.** Otherwise it is not safe to serialize one, but not the other.

**Comment by QuantumClemens** [comment]
Hi @YuanG13 ,
To follow up on Pol's comment, the issue goes back quite deep into the business logic of the online / offline workflow you are using. There is not going to be an easy fix for this particular case, in excess of the workaround we have discussed and that Pol mentioned again. 
I will close this ticket for the moment, but we will keep this in mind for any future re-design work on our internal interfaces.
