### ISSUE TITLE
[BUG] - Output simulator

### ISSUE THREAD

**Issue by YuanG13** [zhinst/laboneq#17]
**Describe the bug**

I was just checking the example notebook.
The new simulator does not give the same results as the old simulator. Please see the following file.
1. For SHFSG there is not Q signal existed.
2. I would assume if the oscillator modulation type is Hardware, the waveform is the envelop, if it is software, the waveform is the envelop together with oscillator frequency. Correct me if it is wrong.
3. Based on the assumption on 2, for measure line, it should be a constant envelop with frequency 1e8 Hz. However, the result shows a waveform with frequency 1e6 Hz.
4. All the devices in the descriptor has sample rate 2GHz, however all the results are showing points with sample rate 20MHz. This may also the cause of problem no.3

**To Reproduce**
1. Define pulse sequence...
6. Execute on hardware / in emulation ...
7. Do additional steps...
8. See error

run the following notebook
[simulator_error.zip](https://github.com/zhinst/laboneq/files/10196820/simulator_error.zip)

**Expected behavior**

**Code & Screenshots**
If possible, add example code or serialized LabOne Q data objects, like the Experiment and DeviceSetup, that allow us to reproduce the behavior. 

**Versions used:**
 - laboneq 1.4
 - zhinst-core 22.8
 - others

**Context**
- [ ] Do you know a workaround for the issue? If yes, please provide a short description. 
- [ ] Does the issue block your experiments?

**Comment by kshirer** [comment]
Hi @YuanG13, thanks for reporting this. There does seem to be an issue for the SG channels of the SHFSG and QC in the plotting of the simulator. The old simulator can still be used, however, with `results = session.run(compiled_experiment,do_simulation=True)` and plots the expected result. 

As for the documentation, we are working on expanding it now. Your assumption is correct that the modulation `HARDWARE` should plot the envelope, whereas `SOFTWARE` modulation should display the waveform with the oscillator frequency. We are looking into why it isn't 1e8 in your case.

**Comment by YuanG13** [comment]
> Hi @YuanG13, thanks for reporting this. There does seem to be an issue for the SG channels of the SHFSG and QC in the plotting of the simulator. The old simulator can still be used, however, with `results = session.run(compiled_experiment,do_simulation=True)` and plots the expected result.

I am not really understanding what you meant, I did the same thing in the example notebook. Moreover, the new simulator has zero waveform if the pulse is pi/2 phase, and that is the example notebook you provided. There are clearly something wrong about the output. And also there is no QC involved, it is your own descriptor `descriptor_shfsg_shfqa_hdawg_pqsc`

**Comment by QuantumClemens** [comment]
fixed in 1.5, closing this issue
