### ISSUE TITLE
[BUG] - Compilation with neartime pulse parameter fails.

### ISSUE THREAD

**Issue by GlaserN** [zhinst/laboneq#18]
**Describe the bug**
Using a neartime sweep parameter as a parameter for a pulse functional breaks the compilation:

```
File ~\miniconda3\envs\wmiqc\lib\site-packages\laboneq\compiler\scheduler\scheduler.py:450, in Scheduler._calculate_play_wave_parameters(self)
    448     v = pulse_parameters[k]
    449     if isinstance(v, ParamRef):
--> 450         pulse_parameters[k] = parameter_values[v.param_name]
    451         has_updates = True
    452 if has_updates:

KeyError: 'drag_param'
```

**To Reproduce**
Exemplarily use the attached experiments.
[experiment.zip](https://github.com/zhinst/laboneq/files/10206802/experiment.zip)

**Versions used:**
 - laboneq: 1.4
 - zhinst-core
 - others

**Context**
- [ ] Do you know a workaround for the issue? If yes, please provide a short description. 
- [ ] Does the issue block your experiments?

**Comment by GlaserN** [comment]
It seems that all neartime loops fail, with this error, including amplitude sweeps. Here is another example with a similar, but different error:


[experiment.zip](https://github.com/zhinst/laboneq/files/10742406/setup.zip)
```
in run                                                            
    self._calculate_play_wave_parameters()                        
  File "/home/badwwmi-016-2qg/anaconda3/envs/wmilab/lib/python3.10/site-packages/laboneq/compiler/scheduler/scheduler.py", line 463, 
in _calculate_play_wave_parameters                                
    amplitude = parameter_values[amplitude.param_name]            
KeyError: 'flux_amp'   
```
L1Q: 1.7.0

**Comment by QuantumClemens** [comment]
@GlaserN - as discussed, we have improved the error reported in these case where the type of sweep is currently not supported by LaBOne Q - if you require specific types of sweeps to be supported in the future, please contact us directly or open a feature request, thanks!

**Comment by GlaserN** [comment]
Was only the error message improved or does also the functionality work now? To my understanding the two cases presented aboce should be compilable, using neartime waveform exchange handled by L1Q. Is this not available yet?

**Comment by QuantumClemens** [comment]
Correct, this is currently not available in near-time, only real-time sweeps. 
I agree that it is feasible with waveform exchange, but currently is not possible automatically. You could realise this yourself using a user function which resamples the waveforms. 
Do I understand correctly that you would like to sweep arbitrary pulse parameters within a near-time loop?

**Comment by GlaserN** [comment]
Yes, this is in general the most interesting use case of neartime loops.
