### ISSUE TITLE
[BUG] - SHF channels not turned off.

### ISSUE THREAD

**Issue by GlaserN** [zhinst/laboneq#22]
**Describe the bug**
The output channels of the SHF devices, especially SHFSG are not turned off in a succeeding experiment if they are not in use. 

**To Reproduce**
Perform experiment with used SHFSG output channel.
Perform experiment where output channel is not used.
--> Output channel will remain on.

**Expected behavior**
Unused output channels should not be on if not in use.

**Code & Screenshots**

**Versions used:**
 - laboneq: 1.6.0
 - zhinst-core
 - others

**Context**
- [ ] Do you know a workaround for the issue? If yes, please provide a short description. 
- [ ] Does the issue block your experiments?

**Comment by kshirer** [comment]
Hi @GlaserN, Thanks for notifying us, we are looking into making this change. Is this currently an issue in your experiment, i.e. does the fact that the channels are not turned off disturb your measurements?

**Comment by GlaserN** [comment]
Yes, it affects some of our measurements, for these we currently turn off of the channels manually using the LabOne UI.

**Comment by QuantumClemens** [comment]
Hi @GlaserN ,
with release 2.4 switching off output channels is no longer don e by default, and we introduced the new functionality to selectively choose lines to turn off. Closing this ticket.
