### ISSUE TITLE
[BUG] - HDAWG: Channels with offset amplitude turn off

### ISSUE THREAD

**Issue by GlaserN** [zhinst/laboneq#23]
**Describe the bug**
For the HDAWG an offset voltage is set. Every session.run call the hdawg signal on the HDAWG goes for a short amount of time to 0 and back to the biased value, with a significant overshoot. Using this for biasing the frequency of the qubits introduces the danger of flux trapping and reduced qubit coherence. 

![PXL_20230209_181320537(1)](https://user-images.githubusercontent.com/20336812/219005145-dece5ec4-49ee-4532-a7f9-00e8e15b1d1d.jpg)

**To Reproduce**
- Use experiment with defined offset_voltages.
- Use session.run()
- Measure output of HDAWG with oscilloscope.
- Drop and spike can be seen for every start of the experiment.

**Expected behavior**
The bias voltage should remain on constantly.

**Versions used:**
 - laboneq: 1.7.0

**Context**
- [ ] Do you know a workaround for the issue? If yes, please provide a short description. 
- [ ] Does the issue block your experiments?

**Comment by kshirer** [comment]
Hi @GlaserN, I have discussed this issue with the team and we are looking into it.

**Comment by QuantumClemens** [comment]
Hi @GlaserN ,
with release 2.4 switching off output channels is no longer done by default, only in situation where it is necessary due to hardware constraints. Closing this ticket.
