### ISSUE TITLE
[Feature] - Allow bytes as pulse functional argument

### ISSUE THREAD

**Issue by GlaserN** [zhinst/laboneq#25]
As discussed. We need to transfer information to our pulses which contain more information than can be express in float, int or complex. We would therefore like to have a possibility to transfer all possible parameters. I see that the requirement for guaranteed serialization results in constraints for passing arbitary pulse argument types. An encoding in a bytes object would enable us to preencode the information, while retaining the full flexibility.

This blocks us from integrating pulse functionals into our framework.

**Comment by kshirer** [comment]
Hi @GlaserN, would types strings, ints, floats, bools, as well as lists, dicts and numpy arrays of these types be sufficient or are bytes required, i.e. what types do you need in addition to float, in, and complex to be able to integrate the pulse functionals?

**Comment by GlaserN** [comment]
Yes, these suggested types would be sufficient for our purposes. Especially strings, dicts and lists are of required for us.
