### ISSUE TITLE
[BUG] - number of measurement points 0 returned by daq from device 'SHFQC/QA:DEV12188' does not match length of recipe measurement_map which is 524288

### ISSUE THREAD

**Issue by GlaserN** [zhinst/laboneq#27]
**Describe the bug**
Executing the following experiment results in the following error:
```
AssertionError: number of measurement points 0 returned by daq from device 'SHFQC/QA:DEV12XXX' does not match length of recipe measurement_map which is 524288
```
[experiment.zip](https://github.com/zhinst/laboneq/files/10865860/experiment.zip)

"laboneq_compiler_settings": {
      "HDAWG_MIN_PLAYWAVE_HINT": 400,
      "HDAWG_FORCE_COMMAND_TABLE": false,
      "SHFSG_FORCE_COMMAND_TABLE": true,
      "SHFSG_MIN_PLAYWAVE_HINT": 128,
      "SHFSG_MIN_PLAYZERO_HINT": 128
    },

**Versions used:**
 - laboneq: 1.7

**Comment by kshirer** [comment]
Hi @GlaserN, we are looking into this now.

**Comment by QuantumClemens** [comment]
@GlaserN - as discussed in our meeting, will close this ticket as implementing https://github.com/zhinst/laboneq/issues/26 should fix this issue.
