### ISSUE TITLE
[BUG] - non-desired waveform envelope of gaussian_q pulse function.

### ISSUE THREAD

**Issue by YuanG13** [zhinst/laboneq#3]
**Describe the bug**
The gaussian_q pulse from laboneq/dsl/experiment/pulse_library.py produces an envelop that is not same as gaussian.

<img width="200" alt="image" src="https://user-images.githubusercontent.com/88106938/195351309-f467c459-3516-4ba5-a8e9-6bb91d515567.png">

<img width="200" alt="image" src="https://user-images.githubusercontent.com/88106938/195351723-0dcc7f7c-9d2b-4141-9d11-18c45563cd97.png">

the first 2 pulses are generated from built-in gaussian pulse, and last 2 are from gaussian_q pulse. The sample points are returned by compiled experiment.

see files below for experiment, devicesetup, and compiled experiment.

[experiment.zip](https://github.com/zhinst/laboneq/files/9765155/experiment.zip)

**Expected behavior**
the gaussian_q has the same envelop as gaussian

**Versions used:**
 - laboneq 1.0.2
 - zhinst-core 22.08

**Comment by YuanG13** [comment]
> Hi @YuanG13 , it seems that the effect you see comes from aliasing. If you want to check, you could plot either the absolute value (real_part^2 + imaginary_part^2) or resample a pulse (e.g., with scipy.signal.resample). It was just coincidence that the effect looks more pronounced on the second pair of pulses (if you look closely, it's also there in the first pair).
> 
> On another note: We'd recommend to use `pulse_library.gaussian(length=50e-9, amplitude=1j)` instead of the `gaussian_q` function.

So only gaussian and const are recommended to be used as built-in function. Other than those two, the pulse should be supplied with pulse gate.

Do you have any agenda to bring other functions? e.g. triangle, Lorentz,or some pulses in labone(ramp, Blackman, etc).

**Comment by kshirer** [comment]
Hi @YuanG13 , just to quickly follow up: As `gaussian_q` is better implemented as @Alectoid described, we plan to remove `gaussian_q` entirely in the upcoming release. 

As for other functions, we are actively working to increase the functionality of the pulse library.
