### ISSUE TITLE
[BUG] - Nested sweeps limitation on memory ?

### ISSUE THREAD

**Issue by Jacfomg** [zhinst/laboneq#30]
**Describe the bug**
Running 2 nested sweep section the outer one has a limited number of points before I got an error from the device running out of free registers:

2023.03.13 15:11:37.057 laboneq.controller.util        CRITICAL SHFQC/QA:DEV12146: AWG compilation failed.
Compilation failed: Compiler Error (line: 26): run out of free registers, please reduce complexity

which Anas Elhamdi mentioned to me "We would expect that this complexity error might be an AWG compiler bug". The purpose is running calibrations like this with higher resolution or range.
![2DSweep](https://user-images.githubusercontent.com/19141117/225291651-d7409981-0b7c-43fc-b85e-c6b6965b7a29.png)

**To Reproduce**

1. Define pulse sequence
2. Execute on hardware
3. Define 2 nested exp.sweep() sections. The one in the outer loop sweeping frequency in my case does not allow more than 20 values. This results on a very low resolution or narrow scan, that makes some calibration routines tricky.
4. 2023.03.13 15:11:37.057 laboneq.controller.util        CRITICAL SHFQC/QA:DEV12146: AWG compilation failed.
Compilation failed: Compiler Error (line: 26): run out of free registers, please reduce complexity

**Expected behavior**
Allow more sweep values on the outer loop.

**Code & Screenshots**
I attach the device_setup, the experiment dictionary generated is huge, around 200MB, so I don't attach it.
[device_setup.zip](https://github.com/zhinst/laboneq/files/10988069/device_setup.zip)
This is the code I would like to run through the integration I'm doing with our library.
[Example_sweeps.zip](https://github.com/zhinst/laboneq/files/10988101/Example_sweeps.zip)
**Versions used:**
 - laboneq 2.1.0

 - zhinst-core  22.8.36541

**Context**
- [ ] Do you know a workaround for the issue? If yes, please provide a short description. 
If this is really an isue the workaround would be to run multiple experiments at the expense of longer number execution and compilation steps
- [ ] Does the issue block your experiments?
Yes, it makes routines that scan multiple parameters like flux vs qubit frequency a bit trickier with a limited amount of points avaliable

**Comment by kshirer** [comment]
Hi @Jacfomg, we are looking into this!

**Comment by YuanG13** [comment]
@QuantumClemens This is the same problem we discussed before, where our situation is in UHFQA.

**Comment by QuantumClemens** [comment]
Hi @Jacfomg, 
the code compression was significantly improved with release 2.4, I will close this ticket. Let us know if you find other issues.
