### ISSUE TITLE
[BUG] - SG: Realtime frequency sweep with two oscillators not working

### ISSUE THREAD

**Issue by GlaserN** [zhinst/laboneq#31]
**Describe the bug**
For measuring the anharmonicity of the qubit we need the perform to pulses with different frequencies via the SHFSG.
For finding the resonance we want to sweep only the e-f transition but not the g-e transition.
Using realtime sweeps for the logical_signal_line with the g-e transition breaks however the behaviour of the outcome measured on the oscilloscope:
The first defined oscillator (for us the g-e) frequency is swept with the range defined for the LinearSweep of the e-f frequency, however around the g-e frequency. The pulse for the e-f frequency is played with the oscillator frequency `0`, e.g., at the lo_frequency.

**To Reproduce**
Compare the output on channel 5 for the both experiments in neartime or realtime on the oscilloscope. 
The neartime experiment produces the expected outcome, however being significantly slower.
[realtime.zip](https://github.com/zhinst/laboneq/files/11052823/realtime.zip)
[neartime.zip](https://github.com/zhinst/laboneq/files/11052829/neartime.zip)

Realtime:
![grafik](https://user-images.githubusercontent.com/20336812/227264374-f5448cb0-1a48-42ed-9954-b349ccb2b351.png)
Sweep between 50-150MHz on wrong pulse
Second pulse: at lo frequency: 600MHz.

Neartime:
![grafik](https://user-images.githubusercontent.com/20336812/227264290-9f2818d5-f72c-49ff-9a5d-6b27c26bf027.png)
Correct behaviour

**Expected behavior**
The realtime sweep should only sweep the oscillator connected to the associated logical signal line.

**Versions used:**
 - laboneq: 2.2
 - zhinst-core: 23.02

**Context**
- [ ] Do you know a workaround for the issue? If yes, please provide a short description. 
- [x] Does the issue block your experiments?

**Comment by QuantumClemens** [comment]
@GlaserN can you confirm if the workaround proposed by @polwel is working for you?

**Comment by QuantumClemens** [comment]
@GlaserN could you please confirm of the workaround is working for you or if you need additional information?

**Comment by GlaserN** [comment]
We can make use of the this workaround. For the general application it would however be useful to have the flexibility to arbitrarily name the oscillators, especially as they are, in our setup, initialized in the order of usage.

**Comment by polw-zi** [comment]
Hi @GlaserN, you can expect a better solution for this issue coming in version 2.12 next week.

**Comment by kshirer** [comment]
Hi @GlaserN , with the release of 2.12, I'm closing this issue.
