### ISSUE TITLE
[Feature] - Check and validate number of available table entries for executeTableEntry already in compiler

### ISSUE THREAD

**Issue by GlaserN** [zhinst/laboneq#33]
**Describe the bug**
SHFSG compilation fails with:

2023.04.23 20:18:59.559 laboneq.controller.util        CRITICAL SHFQC/SG:dev12188: AWG compilation failed.
Compilation failed: Compiler Error (line: 15866): Invalid constant argument used for executeTableEntry
Compiler Error (line: 15869): Invalid table index used for executeTableEntry

**To Reproduce**
Compile and run the attached experiment

[experiment.zip](https://github.com/zhinst/laboneq/files/11304561/experiment.zip)

**Versions used:**
 - laboneq: 2.4.0

**Context**
- [ ] Do you know a workaround for the issue? If yes, please provide a short description. 
- [ ] Does the issue block your experiments?

**Comment by polw-zi** [comment]
Hi @GlaserN, your example exceeds the available command table entries (4095 on SHFSG). The error message should improved, agreed.

I have tried playing around with the compiler settings but I could not get it to compile without waveform memory instead.

I am afraid you'll need to reduce the complexity of the experiment.

cc @kshirer

**Comment by QuantumClemens** [comment]
Changing to feature request as discussed in our meeting

**Comment by QuantumClemens** [comment]
Hi @GlaserN, 
Implemented with version 2.16, please let us know if this works as intended
