### ISSUE TITLE
[BUG] - Measurement only in ground state for complex experiment

### ISSUE THREAD

**Issue by GlaserN** [zhinst/laboneq#34]
**Describe the bug**
Using the attached experiment we only measure the ground state of the qubit, as shown in the following image:
![grafik](https://user-images.githubusercontent.com/20336812/234904531-4b7674d1-5c67-46f8-a383-6876d0e7ef18.png)

After removing sections from the experiment, thus, reducing the complexity we obtain the expected measuremnt result.
![grafik](https://user-images.githubusercontent.com/20336812/234904831-7a0a28bc-4cc8-4e5e-9111-41e6d52619d4.png)

Use the attached Jupyter Notebook and experiment, setup files to reproduce.
[experiment.zip](https://github.com/zhinst/laboneq/files/11345224/experiment.zip)

**Versions used:**
 - laboneq: 2.4.0

**Context**
- [ ] Do you know a workaround for the issue? If yes, please provide a short description. 
- [x] Does the issue block your experiments?

**Comment by kshirer** [comment]
Hi @GlaserN, we are looking into this.

**Comment by QuantumClemens** [comment]
Hi @GlaserN , 
a fix for this is committed, however it was not an issue within LabOne Q but required a change to the awg compiler behavior. The fix will be in the next version of LabOne, currently being tested and expected for release at the end of June. We will ping you again once it is available.

**Comment by hodgestar** [comment]
The new LabOne 23.06 has been released. LabOneQ 2.12 which comes out next week will support the new LabOne.

**Comment by QuantumClemens** [comment]
closing this issue, as discussed above
