### ISSUE TITLE
[BUG] - Undeterministic failed compilation of Feedback experiments

### ISSUE THREAD

**Issue by GlaserN** [zhinst/laboneq#35]
**Describe the bug**
We want to perform experiments with measurement feedback. The compilation fails, however, sometimes with the following error:
```
  File "/home/measure/miniconda3/envs/wmiqc/lib/python3.10/site-packages/laboneq/compiler/code_generator/sampled_event_handler.py", line 603, in close_event_list
    raise LabOneQException(
laboneq.core.exceptions.laboneq_exception.LabOneQException: States missing in match statement with handle Qubit3_00000. First state: 1, last state: 1, number of states: 1, expected 2, starting from 0.
```

When rerunning a Notebook while loading and compiling the same (attached) experiment. We sometimes see this error and sometimes compilation and execution will work.

[feedback.zip](https://github.com/zhinst/laboneq/files/11353879/feedback.zip)

![grafik](https://user-images.githubusercontent.com/20336812/235158827-efa7d7c6-73fc-4157-8441-0ce494ca3382.png)

![grafik](https://user-images.githubusercontent.com/20336812/235158887-f0d8b23b-51d9-41e7-a696-1f1b2f9ab2a0.png)

**Code & Screenshots**
If possible, add example code or serialized LabOne Q data objects, like the Experiment and DeviceSetup, that allow us to reproduce the behavior. 

**Versions used:**
 - laboneq: 2.3.0

**Context**
- [ ] Do you know a workaround for the issue? If yes, please provide a short description. 
- [x] Does the issue block your experiments?

**Comment by kshirer** [comment]
Hi @GlaserN, we are looking into this.

**Comment by QuantumClemens** [comment]
fix has been committed, unfortunately it did not make it into the 2.7 release, will be in 2.8

**Comment by hodgestar** [comment]
@GlaserN 2.8 has been released. Would you be able to try it out and confirm whether this issue is resolved?

**Comment by GlaserN** [comment]
Thanks. It seems to be work now.
