### ISSUE TITLE
[BUG] - Phase increment after specific pulses lead to too exceeding command table entries

### ISSUE THREAD

**Issue by GlaserN** [zhinst/laboneq#36]
**Describe the bug**
For single qubit pulses we oscillator phase incrementations **after** the pulse is played, e.g., as corrections for the next pulse. We implement this by adding an additional play command, only incrementing the oscillator phase. 

This implementation leads however to a very large number of command table entries: **4569** (for a single RB randomization with 800 Cliffords). This number of command table entries exceeds the number of available command table entries.

The whole sequence consists only of **8** building blocks (x,y,x90,y90, -x,-y,-x90,-y90).

[Experiment.zip](https://github.com/zhinst/laboneq/files/11452907/Experiment.zip)

**Versions used:**
 - laboneq:  2.5.0

**Context**
- [ ] Do you know a workaround for the issue? If yes, please provide a short description. 
- [x] Does the issue block your experiments?

**Comment by polw-zi** [comment]
Hi @GlaserN, thanks for reporting. Looks like an issue with rounding errors that produces excessive command table entries that only differ minutely.
