### ISSUE TITLE
[BUG] - Run fails with exit code (0xC0000005)

### ISSUE THREAD

**Issue by GlaserN** [zhinst/laboneq#37]
We run the following experiment, includes a frequency sweep of the SG oscillator.
During session.run the execution is killed with exit code (0xC0000005) without any additional errors.

Compile and run the following experiment:

[experiment.zip](https://github.com/zhinst/laboneq/files/11625200/L1Q-20230601_00044_ss_rspect_mod_realtime-20230601T121921Z-00000.zip)

**Versions used:**
 - laboneq: 2.6.0
 - Windows 10

**Context**
- [ ] Do you know a workaround for the issue? If yes, please provide a short description. 
- [ ] Does the issue block your experiments?

**Comment by zi-2k** [comment]
Not reproducible on my PC, but the symptoms suggest that there may be an issue with the AWG compiler, and possibly related to an incorrect frequency specification resulting in the generation of invalid SeqC code:

```
//...
configFreqSweep(0,-1265000000.0,50000000.0);
//...
```

Does the same error occur even when using the frequency within the allowed range?

**Comment by zi-2k** [comment]
FYI: On my PC I get expectedly:

```
2023.06.01 15:08:52.222 laboneq.controller.util        CRITICAL SHFSG:dev12204: AWG compilation failed.
Compilation failed: Compiler Error (line: 4): invalid value for argument 1 of function configFreqSweep
```

**Comment by GlaserN** [comment]
The sweep frequency was indeed the Issue. Setting this to the allowed range leads to a successfull run.

**Comment by zi-2k** [comment]
It's a lower priority, but we may still want to investigate why it crashed in your case instead of displaying the expected error message. This could potentially be related to the multiprocessing environment.

**Comment by GlaserN** [comment]
Agreed. On this PC this behaviour is also present when just loading and running the provided experiment in a pure jupyter Notebook.

**Comment by zi-2k** [comment]
Is there any possibility of capturing the crash dump?

**Comment by QuantumClemens** [comment]
@GlaserN - as the source of the issue was identified and could be removed, I will close this ticket here. If you can provide the crash dump to @zi-2k , we can still investigate why the expected error message was not present on your system.
