### ISSUE TITLE
[BUG] - Test bug!

### ISSUE THREAD

**Issue by hodgestar** [zhinst/laboneq#40]
**Describe the bug**
Test mirroring of issues to ZI LabOneQ internal issue tracker.

**To Reproduce**
Look at this bug report.

**Expected behavior**
Issue appears in the ZI LabOneQ internal issue tracker.

**Code & Screenshots**
This issue is itself the test case.

**Versions used:**
 - laboneq (latest code on GitHub)

**Context**
- [X] Is this issue self-referential?

**Comment by Knapock** [comment]
Test comment.
