### ISSUE TITLE
[BUG] - QA threshold only set if in acquisition mode discrimination.

### ISSUE THREAD

**Issue by GlaserN** [zhinst/laboneq#41]
**Describe the bug**
The thresholds for the QA are only set when using the acquisition mode `discrimination`. This value is however also used when not using this acquisition mode in case of using feedback results. The node should therefore be generally set if the threshold is defined in the line calibration.

The following experiment is an experiment of setting a threshold, which is not updated on the devices:
[L1Q-20230609_00018_on_off_activeReset-20230609T112358Z-00000.zip](https://github.com/zhinst/laboneq/files/11705821/L1Q-20230609_00018_on_off_activeReset-20230609T112358Z-00000.zip)

**Versions used:**
 - laboneq: 2.8

**Context**
- [ ] Do you know a workaround for the issue? If yes, please provide a short description. 
- [ ] Does the issue block your experiments?

**Comment by zi-2k** [comment]
Hi @GlaserN, thanks for bringing this to our attention. Indeed, in both INTEGRATION and DISCRIMINATION modes, configuring the threshold is necessary as it remains relevant for the HW feedback regardless of the result logger source.

**Comment by QuantumClemens** [comment]
@GlaserN - the fix was released with 2.9, closing this ticket. If you have nay other issues, please let us know.
