### ISSUE TITLE
[BUG] -  'Precompensation' object has no attribute 'has_changed'

### ISSUE THREAD

**Issue by GlaserN** [zhinst/laboneq#42]
**Describe the bug**
When using Precompensation in a signal calibration the following error is raised by the initialization:

```
        if self._mixer_calibration is not None:
            self._mixer_calibration.has_changed().connect(
                self._mixer_calibration_changed_callback
            )
        if self._precompensation is not None:
>           self._precompensation.has_changed().connect(
                self._precompensation_changed_callback
            )
E           AttributeError: 'Precompensation' object has no attribute 'has_changed'

..\..\miniconda3\envs\wmiqconly\lib\site-packages\laboneq\dsl\calibration\signal_calibration.py:92: AttributeError
```

**To Reproduce**
Generate calibration object with precompensation

**Versions used:**
 - laboneq: 2.8.0

**Context**
- [ ] Do you know a workaround for the issue? If yes, please provide a short description. 
- [x] Does the issue block your experiments?

**Comment by GlaserN** [comment]
We imported `laboneq.data.precompensation.Precompensation` instead of `laboneq.dsl.calibration.precompensation.Precompensation` with the correct import the module works as expected.

For a better user experience while importing, I suggest not using the same class names and similar import paths throughout the package.

**Comment by polw-zi** [comment]
Hi Niklas, sorry to hear that you were negatively affected by this, and glad you solved it.

Some context: we are currently in the process of refactoring the internal interfaces between the components, and down the line the types you mention will be fused. Currently, `laboneq.data`, as well as `laboneq.interface` and `laboneq.implementation`, are work-in-progress.

We did indeed not anticipate users accidentally (via some tooling auto-import magic I presume 😉) importing the wrong type. We may consider removing them from the PyPI builds.
