### ISSUE TITLE
[Feature] - Gracefully interrupt neartime loops

### ISSUE THREAD

**Issue by GlaserN** [zhinst/laboneq#43]
When executing neartime steps, we want to stop the experiment if a specific condition is reached.
We would like the option to **gracefully** stop the experiment, e.g., by calling a method of the session object, such that the final required steps by LabOneQ are still executed without starting the next neartime step.

**Describe alternatives or workarounds you have considered**
Raise an exception in the callback function, which is explicitly catched outside the run method.

**Comment by QuantumClemens** [comment]
Hi @GlaserN , 
thanks for the input, we will have a look at how we could best implement this and align with you once we have a plan

**Comment by QuantumClemens** [comment]
Hi @GlaserN, 
Implemented with version 2.16, please let us know if this works as intended
