### ISSUE TITLE
[BUG] - waveform is not uploaded in the spectroscopy mode

### ISSUE THREAD

**Issue by YuanG13** [zhinst/laboneq#45]
**Describe the bug**
In pulsed resonator spectroscopy experiment, 

if there are more than one logical measure signals(for example: measure0, measure1, measure2) in a physical port, and you define a LaboneQ Experiment with experimental signals of all the lines, and define a pulsed resonator spectroscopy experiment on the measure signal which is not the first one(for example measure1 or measure2). 

then, the waveform of the measure pulse is not uploaded to the device, and the experiment is become a CW resonator spectroscopy.
 
**To Reproduce**
see the experiment, device setup, compiled experiment json files for detail.
[issue.zip](https://github.com/zhinst/laboneq/files/11893661/issue.zip)

**Expected behavior**
A pulsed resonator spectroscopy experiment.

**Solution**
****** Please check wether this solution influences other part of the compiler*******
change codes in laboneq.controller.devices.device_zi.py line 818 to 821:
```
idx = 0
while idx in waves_by_index:
    bin_waves.append(waves_by_index[idx])
    idx += 1
```
to 
```
for _ , wave in waves_by_index.items():
    bin_waves.append(wave)
```

**Versions used:**
 - laboneq == 2.4
 - zhinst-core
 - others

**Context**
- [ ] Do you know a workaround for the issue? If yes, please provide a short description. 
- [x] Does the issue block your experiments?

**Comment by YuanG13** [comment]
this issue also happens with integration mode. the waveform signal is also not uploaded properly

**Comment by QuantumClemens** [comment]
@YuanG13 thanks for the additional info, we are looking into this issue
