### ISSUE TITLE
[BUG] - Loading of serizalized MixerType broken

### ISSUE THREAD

**Issue by GlaserN** [zhinst/laboneq#47]
**Describe the bug**
Loading a serialized experiment with a defined MixerType fails with:
```ValueError: 'IQ' is not a valid MixerType```

The serializer tries to instantiate the class with mapped_class(val), which is only valid for const arguments for the definition of the MixerType as introduced in 2.10, MixerType["IQ"] has to be called instead of MixerType("IQ").

**To Reproduce**
Try to load, for example, the following compiled experiment:
[compiledexperiment.zip](https://github.com/zhinst/laboneq/files/12172430/compiledexperiment.zip)

**Expected behavior**
SerializedObject should still be able to load

**Code & Screenshots**
**Versions used:**
 - laboneq: 2.10
 - zhinst-core
 - others

**Context**
- [ ] Do you know a workaround for the issue? If yes, please provide a short description. 
- [ ] Does the issue block your experiments?

**Comment by kshirer** [comment]
Hi @GlaserN, thanks for this. We're looking into it.

**Comment by kshirer** [comment]
Hi @GlaserN , this fix is included in the 2.12 release so I'm closing this issue.
