### ISSUE TITLE
[BUG] - Output simulator cannot be initialised 

### ISSUE THREAD

**Issue by YuanG13** [zhinst/laboneq#48]
**Describe the bug**

run following code in example/01/01_cw_resonator_spec_shfsg_shfqa_shfqc/ipynb
`simulator= OutputSimulator(compiled_res_spec)`

there will be an error `KeyError: 0`

**To Reproduce**
1. Define pulse sequence...
2. Execute on hardware / in emulation ...
3. Do additional steps...

**Expected behavior**

**Code & Screenshots**
If possible, add example code or serialized LabOne Q data objects, like the Experiment and DeviceSetup, that allow us to reproduce the behavior. 

**Versions used:**
 - laboneq= 2.11
 - zhinst-core
 - others

**Context**
- [ ] Do you know a workaround for the issue? If yes, please provide a short description. 
- [ ] Does the issue block your experiments?

**Comment by QuantumClemens** [comment]
@YuanG13 - thanks for notifying us, will look at this

**Comment by QianmuZI** [comment]
Hi @YuanG13 , as discussed, we close this ticket.
