### ISSUE TITLE
[BUG] - Using two HDAWG not possible if UHFQA is used.

### ISSUE THREAD

**Issue by GlaserN** [zhinst/laboneq#5]
**Describe the bug**
If setup includes an UHFQA and two HDAWGs are defined in the setup the following error appears:
```
laboneq.controller.util        CRITICAL HDAWG:DEV8303: Unsupported DIO mode DIOConfigType.HDAWG for device type: HDAWG.
2022.10.13 12:11:46.401 laboneq.controller.util        CRITICAL HDAWG:DEV8303: Unsupported DIO mode DIOConfigType.HDAWG for device type: HDAWG.
2022.10.13 12:11:46.402 wmiqc.core.execution           ERROR  HDAWG:DEV8303: Unsupported DIO mode DIOConfigType.HDAWG for device type: HDAWG.
2022.10.13 12:11:46.401 laboneq.controller.util        CRITICAL HDAWG:DEV8303: Unsupported DIO mode DIOConfigType.HDAWG for device type: HDAWG.
```

**To Reproduce**
The following setup was used.

[setup.zip](https://github.com/zhinst/laboneq/files/9775564/setup.zip)

**Expected behavior**
This setup should be possible.

**Code & Screenshots**

**Versions used:**
 - laboneq: 1.0.0
 - zhinst-core
 - others

**Context**
- [ ] Do you know a workaround for the issue? If yes, please provide a short description. 
- [x] Does the issue block your experiments?

**Comment by polwel** [comment]
We can reproduce the issue with the provided setup, and are investigating.

**Comment by polwel** [comment]
I think the issue is that the device configuration is missing the PQSC -> AWG_FLUX connection.

I certainly agree that the error message is unhelpful, though.

@kshirer

**Comment by kshirer** [comment]
To elaborate on Pol's comment, in `instruments`, under the PQSC, a second connection to the AWG_FLUX is necessary. At the moment, no ZSYNC port for the second HDAWG 'AWG_FLUX` is specified in the PQSC. An additional connection specifying the                         `local_port`, `remote_path`, `remote_port`, and `signal_type` for AWG_FLUX is needed.

**Comment by GlaserN** [comment]
Thanks for the investigation. Indeed, specifzing the PQSC solves this issue.
