### ISSUE TITLE
[BUG] - has_onboard_lo does not work for SHFQC

### ISSUE THREAD

**Issue by GlaserN** [zhinst/laboneq#53]
**Describe the bug**
The `has_onboard_lo` function in `laboneq.dsl.utils` returns False for SHFQC devices.

**To Reproduce**
Create a device setup with an SHFQC device and a connected logical signal line. Try to get the property of a logical signal line.

**Expected behavior**
Should return True

It seems that the `device_type` has been changed to also allow for "SHFQC". The check has, therefore, to be changed 
from 
`if device_type in ["SHFQA", "SHFSG"]:`
to:
`if device_type in ["SHFQA", "SHFSG", "SHFQC"]:`

**Versions used:**
 - laboneq: 2.18
 - zhinst-core
 - others

**Context**
- [ ] Do you know a workaround for the issue? If yes, please provide a short description. 
- [ ] Does the issue block your experiments?

**Comment by QuantumClemens** [comment]
Hi @GlaserN ,
thanks for noticing and diagnosing, fix will be deployed in 2.19 next week.
