### ISSUE TITLE
[BUG] - Neartime loop caller broken

### ISSUE THREAD

**Issue by GlaserN** [zhinst/laboneq#54]
**Describe the bug**
The neartime loop call function can receive the values of the neartime loops. Since L1Q 2.18 the function does not receive the value of the loop, but instead just the name of the uid. It is therefore not possible anymore to obtain the respective NT step.

**To Reproduce**
Create an experiment that calls a neartime loop function and give it a neartime Parameter.
like:
  self.loop_section.call(
                  func_name="neartime_loop_call",
                  **{k: k for k in neartime_loops},
              )
Check the respective elements in the neartime_loop_call function

**Expected behavior**
Get the sweep value at the current step.

**Code & Screenshots**

**Versions used:**
 - laboneq: 2.18
 - zhinst-core
 - others

**Context**
- [ ] Do you know a workaround for the issue? If yes, please provide a short description. 
- [ ] Does the issue block your experiments?

**Comment by kshirer** [comment]
Hi @GlaserN , thanks for the report; we're looking into this.

**Comment by polw-zi** [comment]
Hi @GlaserN I cannot reproduce your issue. In our tests sweep parameters are correctly resolved to their value.

Looking at your snippet, could you be actually passing the string rather than the parameter object?

```python
self.loop_section.call(
    func_name="neartime_loop_call",
    **{k: k for k in neartime_loops},
)
```
Passing the `kwargs` object like this with `k` being both the key and the value requires that `k` is a string. Are you missing an `items()` perhaps?

**Comment by polw-zi** [comment]
Ok, we think we see what's causing your issue.

Previously, when passing sweep parameters to `call()`, they were internally encoded by their UID. This was an implementation detail however; it leaked for example, when trying to pass a regular string. In recent versions we are now encoding the parameter properly, so it does not collide with general strings.

Your code seems to have relied on accidental behavior where passing a string with the parameter UID would resolve to the parameter value.

Instead, pas the parameter object itself, not its UID.

**Comment by GlaserN** [comment]
Thanks for investigating and clarifying. This solved the Issue.
