### ISSUE TITLE
[Feature] - Raise Exception on failing pulse replacement

### ISSUE THREAD

**Issue by GlaserN** [zhinst/laboneq#55]
When performing pulse replacement, this is according to the logged messages of L1Q, not possible:
 `Pulse replacement on pulses that allow compression not allowed.` 
This notification is only logged, but not actually raised. As this behavior will lead to wrong experiments this case should raise a real exception in Python.

L1Q: 2.17

**Comment by QuantumClemens** [comment]
Hi @GlaserN , thanks for reporting, this feature will be deployed with the next release

**Comment by QuantumClemens** [comment]
Closing this ticket, please let us know if any issues appear with the feature
