### ISSUE TITLE
Warning: instance of class NumpyArrayRepr may not serialize properly

### ISSUE THREAD

**Issue by picbeats** [zhinst/laboneq#56]
Serialization of compiled experiment logs warning

"instance of class NumpyArrayRepr may not serialize properly"

I believe it's because parameters:  `entities_collector` and `whitelist` are reversed here: 

https://github.com/zhinst/laboneq/blob/3f2206d9ece770ecefa003fe5a4826dc27e16197/laboneq/core/serialization/simple_serialization.py#L475

**Comment by QuantumClemens** [comment]
Thanks for reporting and diagnosing @picbeats, we are working on it.

**Comment by QuantumClemens** [comment]
This issue has been fixed - closing the ticket.
