### ISSUE TITLE
[BUG] - Sequential averaging mode broken

### ISSUE THREAD

**Issue by GlaserN** [zhinst/laboneq#6]
**Describe the bug**
Sequential averaging mode can not be used with L1Q

- [ ]  A: Measured results have unexpected / wrong results

-- Sequential
![tracked_spectroscopy_data_plot](https://user-images.githubusercontent.com/20336812/196963890-5365d4bb-8732-4327-b2ea-13be11b9d5ef.png)

[experiment.zip](https://github.com/zhinst/laboneq/files/9830583/experiment.zip)

-- Cyclic
![tracked_spectroscopy_data_plot](https://user-images.githubusercontent.com/20336812/196963964-bc53a2e9-5de1-4fcf-b6ab-e47f77676089.png)

[experiment.zip](https://github.com/zhinst/laboneq/files/9830579/experiment.zip)

- [ ]  B: Compilation does takes forever with LinearSweepParameters 
Cyclic:
[experiment.zip](https://github.com/zhinst/laboneq/files/9830591/experiment.zip)
Sequential:
[experiment.zip](https://github.com/zhinst/laboneq/files/9830593/experiment.zip)

**To Reproduce**
Execute experiments with above experiments using the following setup.
[setup.zip](https://github.com/zhinst/laboneq/files/9830614/setup.zip)

**Expected behavior**
A) The results of the experiments should be qualitatively the same
B) It should be possible to compile the experiment in sequential mode without substantial overhead.

**Code & Screenshots**

**Versions used:**
 - laboneq: 1.0.0
 - zhinst-core
 - others

**Context**
- [ ] Do you know a workaround for the issue? If yes, please provide a short description. 
- [ ] Does the issue block your experiments?

**Comment by Alectoid** [comment]
Hi @GlaserN , a short update: We could reproduce both issues.
A) Currently, our compiler does not support multiple `acquire` statements within one real-time acquisition loop in sequential mode. As I understood from @zi-2k, this is not blocking for you?
B) We are currently testing a fix (which will probably go into 1.4) and have a new regression test in place that checks for the compilation times both in sequential and cyclic averaging.

**Comment by Alectoid** [comment]
Hi @GlaserN ,
With release 1.3 coming this week, compilation times in `Sequential` mode will be back to fast!
