### ISSUE TITLE
[BUG] - compilation error for specific experiment configuration

### ISSUE THREAD

**Issue by maxwmi** [zhinst/laboneq#60]
**Describe the bug**
We are running a typical Ramsey experiment, where the phase is swept linearly with the delay time. When compiling with 121 sweep steps (rendered in individual sequences) the experiment works fine, but for 51 sweep steps the compilation fails.

I have attached the Laboneq intermediates for review
**To Reproduce**
compile the attached experiment files

**Expected behavior**
both experiments should compile fine

**Code & Screenshots**
If possible, add example code or serialized LabOne Q data objects, like the Experiment and DeviceSetup, that allow us to reproduce the behavior. 

**Versions used:**
 - laboneq 23.06
[L1Q-20240112_00024_ramsey_xy-20240112T094418Z-00000.zip](https://github.com/zhinst/laboneq/files/13917824/L1Q-20240112_00024_ramsey_xy-20240112T094418Z-00000.zip) this experiment is working (121 sequences) 

[L1Q-20240112_00025_ramsey_xy-20240112T094548Z-00000.zip](https://github.com/zhinst/laboneq/files/13917836/L1Q-20240112_00025_ramsey_xy-20240112T094548Z-00000.zip) this experiment is failing (51 sequences)

**Comment by QuantumClemens** [comment]
Hi @maxwmi , 

thanks for letting us know of this bug. Could you provide the error message you receive as well as the labone q version that you used, the info you provided seems to be the LabOne version?

**Comment by maxwmi** [comment]
Hi clemens, 

Sorry tianmu also mentioned this - I am using laboneq 2.13.0 

The only error message I receive is a compilation failure

**Comment by QuantumClemens** [comment]
Is there a reason why you are using such an old version of LabOne Q? I just tried to compile your examples on the latest release and it worked out of the box, likely this issue has been fixed in the mean time.

**Comment by QuantumClemens** [comment]
@maxwmi is this still an issue for you? From our tests this works in later versions of LabOne Q - I tend to close this ticket.

**Comment by maxwmi** [comment]
I have not done more tests, but I guess it is not worth keeping a bug around on an old version. If it persists with the latest version I can still open a new ticket
