### ISSUE TITLE
Implementing a continuous waveform (simple sine wave) through laboneq

### ISSUE THREAD

**Issue by paniash** [zhinst/laboneq#62]
Hi,

I was wondering if there is a way to implement a continuous sine waveform with a user-specified amplitude, phase, dc offset and frequency. I couldn't find any such implementation in the user guide.

Many thanks!

**Comment by QuantumClemens** [comment]
Hi @paniash , 
that is in fact one of the core functionalities of LabOne Q - what you are describing is what we call a pulse, see e.g. https://docs.zhinst.com/labone_q_user_manual/concepts/sections_and_pulses/pulse_commands/. 
A pulse is a waveform envelope, which may contain amplitudes, phases and offsets. The pulse is played back on a logical signal line (similar to the `frame` concept in QASM, which contains information on modulation frequency and other configuration parameters. 
This example notebook may also help: https://github.com/zhinst/laboneq/blob/main/examples/00_reference/04_pulse_library.ipynb 
or have a look at some of our tutorial videos - https://www.youtube.com/playlist?list=PLjxUCNDRYw8k1_HTzXDohUHKhYKYFQrbn 
Hope this answers the question, let us know if anything more is unclear. What are you planning to use LabOne Q for?
