### ISSUE TITLE
[Feature Request] - Voltage offsets for RF channels on HDAWG

### ISSUE THREAD

**Issue by maxwmi** [zhinst/laboneq#7]
**Describe the current situation**
If a channel is configured as a simple RF channel the voltage offset calibration seems to be not applied. This is working correctly for IQ channels. 
**To Reproduce**
1. load experiment files into session
2. run session
3. see LabOne Gui for offsets (remain at zero for the flux_line channel, in this case 3)

**Expected behavior**
offsets are set to specified value 

**Code & Screenshots**
If possible, add example code or serialized LabOne Q data objects, like the Experiment and DeviceSetup, that allow us to reproduce the behavior. 
[setup.zip](https://github.com/zhinst/laboneq/files/9861113/setup.zip)
The offsets on the "flux_line" channel are not correctly applied, but the same parameter on "drive_line" works as intended.

**Comment by QuantumClemens** [comment]
@maxwmi changed this to a feature request, as the original way you were trying to apply the voltage offsets (through the mixer calibration) is not supported on rf channels - we are onto it

**Comment by YuanG13** [comment]
Hi Clemens, is this the same thing we are having now? that we set dc-offset through toolkit session device object or laboneq session devices[address].

**Comment by QuantumClemens** [comment]
Hi @YuanG13 , this is intended to replace the setting of voltage offsets through toolkit - the idea is to have a calibration setting also for rf_channels that allows to specify these offsets, similar to how it is currently done for iq_channels (where it is part of the mixer_calibration).

**Comment by YuanG13** [comment]
Then is it possible that also including the output range inside the mixer_calibration, which it is also set through Toolkit-like device object together with dc-offset for rf_channel right now on our code.

**Comment by QuantumClemens** [comment]
> Then is it possible that also including the output range inside the mixer_calibration, which it is also set through Toolkit-like device object together with dc-offset for rf_channel right now on our code.

Hi @YuanG13 - I do not understand this comment, what is your suggestion?

**Comment by YuanG13** [comment]
`
def _generate_transaction(self, line: str, DC_offset: Optional[float]):
        _, target_address, ports, _, device_type = get_device(
            self._qpu, line
        )
        for port in ports:
            if device_type == "HDAWG":
                sigout = int(port.split("/")[1])
                range = 5  # Volt
            elif device_type == "SHFSG":
                sigout = int(port.split("/")[1])
                range = 10  # dBm
            transaction = {"sigout": sigout, "DC_offset": DC_offset, "range": range}
            self._transactions[target_address].append(transaction)
def execute_transactions(self) -> None:
        for address, transaction_list in self._transactions.items():
            device = self._session.devices[address]
            with device.set_transaction():
                for transaction in transaction_list:
                    offset = transaction.get("DC_offset", None)
                    if offset is not None:
                        device.sigouts[transaction["sigout"]].offset(offset)
                    device.sigouts[transaction["sigout"]].range(transaction["range"])
`

right now, we also set output range of the rf_channel through toolkit-like device object together with dc_offset. So if you are going to include the dc_offset to mixer_calibration, is it possible that output range also is included.

**Comment by QuantumClemens** [comment]
Thanks for the clarification - yes, that is planned - in fact, not as part of the mixer_calibration property, but as separate part of the calibration.

**Comment by YuanG13** [comment]
good to hear. thanks!

**Comment by GlaserN** [comment]
Is there any update on this Issue? Using the voltage_offset value does still not seem to work in the current release.

**Comment by QuantumClemens** [comment]
@GlaserN thanks for reminding us, this has been deployed with 1.4 already, please use SignalCalibration(voltage_offset=my_offset) for the calibration of the rf_signal. Will close this feature request here, please let us know if there are any additional issues.
