### ISSUE TITLE
[BUG] - Failing dependency resolution with poetry

### ISSUE THREAD

**Issue by GlaserN** [zhinst/laboneq#8]
**Describe the bug**
We are trying to install laboneq using the poetry package manager.

**To Reproduce**
create poetry package
`poetry new poetry-laboneq`
go into poetry package
`cd poetry-laboneq`
try adding laboneq
`poetry add laboneq -vv`

**Expected behavior**
Poetry should be abe to install laboneq from pypi

Instead it gets stuck when resolving for zhinst-toolkit
```
   1: fact: zhinst-toolkit (0.4.2) depends on zhinst-utils (>=0.1.2)
   1: fact: zhinst-toolkit (0.4.2) depends on zhinst-core (>=22.08)
   1: fact: zhinst-toolkit (0.4.2) depends on numpy (>=1.13)
   1: selecting zhinst-toolkit (0.4.2)
   1: fact: zhinst-toolkit (0.4.2) depends on pyelftools (>=0.29)
   1: fact: zhinst-toolkit (0.4.2) depends on typing-extensions (>=4.1.1)
   1: fact: zhinst-toolkit (0.4.2) depends on jsonref (>=0.2)
   1: fact: zhinst-toolkit (0.4.2) depends on jsonschema (>=3.2.0)
   1: fact: zhinst-toolkit (0.4.2) depends on zhinst-utils (>=0.1.2)
   1: fact: zhinst-toolkit (0.4.2) depends on zhinst-core (>=22.08)
   1: fact: zhinst-toolkit (0.4.2) depends on numpy (>=1.13)
   1: selecting zhinst-toolkit (0.4.2)
```

**Code & Screenshots**

**Versions used:**
 - laboneq: 1.1
 - zhinst-core
 - poetry: 1.1.7

**Context**
- [ ] Do you know a workaround for the issue? If yes, please provide a short description. 
- [ ] Does the issue block your experiments?
- [x] It blocks upgrading to LabOneQ 1.1

**Comment by GlaserN** [comment]
Looking further into the log files showed that zhinst core is incosistently referenced in zhinst and zhinst-toolkit.

It seems that the definition of zhinst-toolkit (22.08 with the additional zero) does not correspond to the official versioning on PyPi.

   1: fact: zhinst (22.8.2) depends on zhinst.core (22.8.35048)
   1: fact: zhinst-toolkit (0.4.2) depends on zhinst-core (>=22.08)

**Comment by QuantumClemens** [comment]
Many thanks @GlaserN , we will look into this and let the toolkit developer team know. Pulling in @tobiasah

**Comment by tobiasah** [comment]
Thanks for reporting this. 
Although it is allowed by [PEP440](https://peps.python.org/pep-0440/#integer-normalization) to use leading zeros (since the versions are converted from string to integer) and the problem is therefore with `poetry` there is no good reason why we use this leading slash. 
I therefor removed it to ensure compatibility with poetry.

**Comment by Alectoid** [comment]
Hi  @GlaserN, I have just installed LabOne Q 1.2 (released a couple of minutes ago) with poetry and it worked nicely. Could you please confirm?

**Comment by GlaserN** [comment]
Thanks, the installation works now nicely.
