### ISSUE TITLE
[BUG] - QCCS does not reconnect to PQSC

### ISSUE THREAD

**Issue by GlaserN** [zhinst/laboneq#9]
**Describe the bug**
It seems that if a connection is lost for a short time to the PQSC LabOneQ will try infinitely try setting nodes on the device.

![grafik](https://user-images.githubusercontent.com/20336812/199929074-1630ac64-21c3-4570-b27d-1068d0ffe05e.png)

During these messages the device was visible in LabOne however without actual connection. When manually enabling the PQSC in the device connection WebInterface the execution of LabOneQ script continues. 

**Expected behavior**
LabOneQ should either
 - be able to reconnect to the device
 - Not be stuck in an infinite error loop

**Versions used:**
 - laboneq: 1.0
 - zhinst-core: 22.08
 - others

**Context**
- [ ] Do you know a workaround for the issue? If yes, please provide a short description. 
- [ ] Does the issue block your experiments?

**Comment by QuantumClemens** [comment]
As discussed in our meeting, to prevent this kind of situation, we will investigate introducing a hard fail in the "device not found" error case. 
As the error is at this point not reproducible, I will close this ticket, but will keep you informed about the state of the above feature.
